### ISSUE TITLE
All 0's for checking with user specified lambda

### ISSUE THREAD

**Issue by nsahr** [pbreheny/grpreg#15]
library(grpreg)
data("Birthwt")
X <- Birthwt$X
group <- Birthwt$group
y <- Birthwt$bwt
fit <- grpreg(X, y, group, penalty="grLasso")
Lambda <- fit$lambda
check <- grpreg(X,y,group,lambda=Lambda)
check$beta 

Using the above code, I was trying to be able to check the results by specifying lambda myself. However, when I do this, it results in all 0's.

**Comment by pbreheny** [comment]
Thank you *very* much for pointing this out.  This is now fixed by commit b856d08c351f7c4607bb4af65a7ee48c30405413, which will appear in the next version of grpreg, 3.1-2, which I just submitted to CRAN.

In case you're curious, grpreg 3.1 implemented screening rules for group lasso to make it run faster, but these don't work correctly if the user specifies lambda, which is what was causing the problems.
