### ISSUE TITLE
Options to exclude the intercept

### ISSUE THREAD

**Issue by mynanshan** [pbreheny/grpreg#30]
Hi, thanks for developing such a good package on group regularization. It is extremely useful as it not only integrates a bunch of penalties but also has the option for several probability distributions.
 
I am currently working on an algorithm, in which a group Lasso regression is performed without intercept. However, there is no option as `intercept=FALSE`. If you could add feature it would be very helpful.

**Comment by pbreheny** [comment]
Perhaps you can explain more about the algorithm and why it would be useful, but my reasons for not having such an option are described here: https://github.com/pbreheny/ncvreg/issues/6.

**Comment by mynanshan** [comment]
Thanks for the reply and I agree with your reasons.
In my case, in short, the design matrix `X` is specific (without the column of constant `1` for intercept). As you have pointed out, the estimated coefficients only have small changes with and without an intercept using `glmnet`.
However, as the coefficient estimation performance is going to be rigorously assessed  (and to be compared with other methods), I would like to have a more precise implementation.

**Comment by mynanshan** [comment]
> Perhaps you can explain more about the algorithm and why it would be useful, but my reasons for not having such an option are described here: [pbreheny/ncvreg#6](https://github.com/pbreheny/ncvreg/issues/6).

Thanks for the reply and I agree with your reasons.
In my case, in short, the design matrix `X` is specific (without the column of constant `1` for intercept). As you have pointed out, the estimated coefficients only have small changes with and without an intercept using `glmnet`.
However, as the coefficient estimation performance is going to be rigorously assessed  (and to be compared with other methods), I would like to have a more precise implementation.

**Comment by guzhiling** [comment]
Hi Patrick, thank you for your responses and valuable discussions here and https://github.com/pbreheny/ncvreg/issues/6. I know my issue could be of interest for few, but I thought you might have some insights into this. In short, I have the same question as @mynanshan  and @suolisuoli due to a specific form of design matrix.  

This occurs when I was trying to conduct studies for **negative binomial** responses.  I found this package sparseGAM::grpreg.nb by Ray (https://rdrr.io/cran/sparseGAM/src/R/grpreg.nb.R) where grpreg::grpreg serves as its core function after the author applies the result of [Wang&Leng (2007)](https://www.jstor.org/stable/27639944?seq=1). But I did not find a robust way to implement this function when several covariates are forced to be unpenalized.

As I was going through your [paper](https://link.springer.com/article/10.1007/s11222-013-9424-2) and [source code](https://github.com/pbreheny/grpreg/blob/master/src/lcdfit_glm.c), I wonder if it is feasible to include negative binomial. It seems to me the key functions to be updated are 158-176 in gdfit_glm.c and lcd_glm.c, is it correct?  I would be happy to help with this extension if you think it is feasible. Thanks a lot for your time!
